# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file './new_systerm/new_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QApplication


class  Login_window(QWidget):
    def __init__(self):
        super(Login_window, self).__init__()
        self.setupUi()
        self.show()
        self.connect()


    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(451, 341)

        self.widget = QtWidgets.QWidget(self)
        self.widget.setGeometry(QtCore.QRect(0, 20, 451, 341))
        self.widget.setStyleSheet("#widget{\n"
"background-color:white;\n"
"border: 0px solid gray;\n"
"}")
        self.widget.setObjectName("widget")
        self.password_button = QtWidgets.QPushButton(self.widget)
        self.password_button.setGeometry(QtCore.QRect(78, 10, 113, 32))
        self.password_button.setStyleSheet("#password_button{\n"
"border:0pxl;\n"
"font:12pt \".AppleSystemUIFont\" ;\n"
"   color:gray;\n"
"}\n"
"#password_button::hover{\n"
"color:rgb(18,150,219);\n"
"}")
        self.password_button.setObjectName("password_button")

        self.message_button = QtWidgets.QPushButton(self.widget)
        self.message_button.setGeometry(QtCore.QRect(255, 10, 111, 32))
        self.message_button.setStyleSheet("#message_button{\n"
"\n"
"border:0px  ;\n"
"    font: 12pt \".AppleSystemUIFont\" ;\n"
"    color:gray;\n"
"\n"
"}\n"
"#message_button::hover{\n"
"color:rgb(18,150,219);}\n"
"")
        self.message_button.setObjectName("message_button")
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setGeometry(QtCore.QRect(211, 16, 20, 21))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget)
        self.stackedWidget.setGeometry(QtCore.QRect(30, 50, 401, 251))
        self.stackedWidget.setStyleSheet("#stackedWidget\n"
"{background-color:white;}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.listWidget = QtWidgets.QListWidget(self.page)
        self.listWidget.setGeometry(QtCore.QRect(40, 30, 321, 51))
        self.listWidget.setStyleSheet("#listWidget{\n"
"background-color:white;\n"
"border-radius:10px;\n"
"border:1px solid gray;\n"
"}")
        self.listWidget.setObjectName("listWidget")
        self.listWidget_2 = QtWidgets.QListWidget(self.page)
        self.listWidget_2.setGeometry(QtCore.QRect(40, 90, 321, 51))
        self.listWidget_2.setStyleSheet("#listWidget_2{\n"
"background-color:white;\n"
"border-radius:10px;\n"
"border:1px solid gray;\n"
"}")
        self.listWidget_2.setObjectName("listWidget_2")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(50, 45, 41, 20))
        self.label.setStyleSheet("\n"
"font: 10pt \"黑体\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(50, 104, 41, 21))
        self.label_2.setStyleSheet("font: 10pt \"黑体\";")
        self.label_2.setObjectName("label_2")
        # 错误提示label
        self.warningLabel = QtWidgets.QLabel(self.page)
        self.warningLabel.setGeometry(QtCore.QRect(120, 0, 150, 25))
        self.warningLabel.setStyleSheet("#warningLabel{\n"
                                        "border: 0px;\n"
                                        "color: rgb(217,48,37);\n"
                                        "}")
        self.warningLabel.setObjectName("warningLabel")
        self.user_linedit = QtWidgets.QLineEdit(self.page)
        self.user_linedit.setGeometry(QtCore.QRect(100, 40, 251, 31))
        self.user_linedit.setStyleSheet("#lineEdit{\n"
"border:0xp;\n"
"}")
        self.user_linedit.setObjectName("user_linedit")
        self.password_linedit = QtWidgets.QLineEdit(self.page)
        self.password_linedit.setGeometry(QtCore.QRect(100, 100, 251, 31))
        self.password_linedit.setStyleSheet("#lineEdit_2{\n"
"border:0xp;\n"
"}")
        self.password_linedit.setObjectName("password_linedit")
        self.radioButton = QtWidgets.QRadioButton(self.page)
        self.radioButton.setGeometry(QtCore.QRect(50, 160, 115, 19))
        self.radioButton.setStyleSheet("#radioButton{\n"
"font: 9pt \"黑体\";\n"
"}\n"
"#radioButton::checked{\n"
"color:rgb(30, 188, 255);\n"
"}\n"
"#radioButton::indicator{\n"
"color:rgb(30, 188, 255);\n"
"}")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.page)
        self.radioButton_2.setGeometry(QtCore.QRect(240, 160, 115, 19))
        self.radioButton_2.setStyleSheet("#radioButton_2{\n"
"font: 9pt \"黑体\";\n"
"}\n"
"#radioButton_2::checked{\n"
"color:rgb(30, 188, 255);\n"
"}\n"
"#radioButton_2::indicator{\n"
"color:rgb(30, 188, 255);\n"
"}")
        self.radioButton_2.setObjectName("radioButton_2")
        self.login_button = QtWidgets.QPushButton(self.page)
        self.login_button.setGeometry(QtCore.QRect(120, 200, 141, 41))
        self.login_button.setStyleSheet("#login_button{\n"
"font: 10pt \"黑体\";\n"
"color:white;\n"
"background-color:rgb(0,174,236);\n"
"border:0xp;\n"
"border-radius:10px;\n"
"}")
        self.login_button.setObjectName("login_button")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.page_2)
        self.stackedWidget_2.setGeometry(QtCore.QRect(0, 0, 391, 251))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_3 = QtWidgets.QLabel(self.page_3)
        self.label_3.setGeometry(QtCore.QRect(140, 10, 81, 21))
        self.label_3.setStyleSheet("font: 12pt \"黑体\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.page_3)
        self.label_4.setGeometry(QtCore.QRect(120, 40, 131, 20))
        self.label_4.setStyleSheet("font: 10pt \"黑体\";")
        self.label_4.setObjectName("label_4")
        self.warningLabel2 = QtWidgets.QLabel(self.page_3)
        self.warningLabel2.setGeometry(QtCore.QRect(80, 200, 120, 25))
        self.warningLabel2.setStyleSheet("#warningLabel2{\n"
                                        "border: 0px;\n"
                                        "color: rgb(217,48,37);\n"
                                        "}")
        self.warningLabel2.setObjectName("warningLabel2")
        self.nameLineEdit = QtWidgets.QLineEdit(self.page_3)
        self.nameLineEdit.setGeometry(QtCore.QRect(80, 130, 231, 41))
        self.nameLineEdit.setStyleSheet("* {\n"
"    outline: none;\n"
"}\n"
"\n"
"QDialog {\n"
"    background: white;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #A0A0A0; /* 边框宽度为1px，颜色为#A0A0A0 */\n"
"    border-radius: 10px; /* 边框圆角 */\n"
"    padding-left: 5px; /* 文本距离左边界有5px */\n"
"    background-color: white; /* 背景颜色 */\n"
"    color: #A0A0A0; /* 文本颜色 */\n"
"    selection-background-color: #A0A0A0; /* 选中文本的背景颜色 */\n"
"    selection-color: #F2F2F2; /* 选中文本的颜色 */\n"
"    font-family: \"Microsoft YaHei\"; /* 文本字体族 */\n"
"    font-size: 10pt; /* 文本字体大小 */\n"
"}\n"
"\n"
"QLineEdit:hover { /* 鼠标悬浮在QLineEdit时的状态 */\n"
"    border: 1px solid #298DFF;\n"
"    border-radius: 3px;\n"
"    background-color: white;\n"
"    color: #298DFF;\n"
"    selection-background-color: #298DFF;\n"
"    selection-color: #F2F2F2;\n"
"}\n"
"\n"
"QLineEdit[echoMode=\"2\"] { /* QLineEdit有输入掩码时的状态 */\n"
"    lineedit-password-character: 9679;\n"
"    lineedit-password-mask-delay: 2000;\n"
"}\n"
"\n"
"QLineEdit:disabled { /* QLineEdit在禁用时的状态 */\n"
"    border: 1px solid #CDCDCD;\n"
"    background-color: #CDCDCD;\n"
"    color: #B4B4B4;\n"
"}\n"
"\n"
"QLineEdit:read-only { /* QLineEdit在只读时的状态 */\n"
"    background-color: #CDCDCD;\n"
"    color: #F2F2F2;\n"
"}\n"
"")
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.workerIdLineEdit = QtWidgets.QLineEdit(self.page_3)
        self.workerIdLineEdit.setGeometry(QtCore.QRect(80, 70, 231, 41))
        self.workerIdLineEdit.setStyleSheet("* {\n"
"    outline: none;\n"
"}\n"
"\n"
"QDialog {\n"
"    background: #D6DBE9;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #A0A0A0; /* 边框宽度为1px，颜色为#A0A0A0 */\n"
"    border-radius: 10px; /* 边框圆角 */\n"
"    padding-left: 5px; /* 文本距离左边界有5px */\n"
"    background-color: white; /* 背景颜色 */\n"
"    color: #A0A0A0; /* 文本颜色 */\n"
"    selection-background-color: #A0A0A0; /* 选中文本的背景颜色 */\n"
"    selection-color: #F2F2F2; /* 选中文本的颜色 */\n"
"    font-family: \"Microsoft YaHei\"; /* 文本字体族 */\n"
"    font-size: 10pt; /* 文本字体大小 */\n"
"}\n"
"\n"
"QLineEdit:hover { /* 鼠标悬浮在QLineEdit时的状态 */\n"
"    border: 1px solid #298DFF;\n"
"    border-radius: 3px;\n"
"    background-color: white;\n"
"    color: #298DFF;\n"
"    selection-background-color: #298DFF;\n"
"    selection-color: #F2F2F2;\n"
"}\n"
"\n"
"QLineEdit[echoMode=\"2\"] { /* QLineEdit有输入掩码时的状态 */\n"
"    lineedit-password-character: 9679;\n"
"    lineedit-password-mask-delay: 2000;\n"
"}\n"
"\n"
"QLineEdit:disabled { /* QLineEdit在禁用时的状态 */\n"
"    border: 1px solid #CDCDCD;\n"
"    background-color: #CDCDCD;\n"
"    color: #B4B4B4;\n"
"}\n"
"\n"
"QLineEdit:read-only { /* QLineEdit在只读时的状态 */\n"
"    background-color: #CDCDCD;\n"
"    color: #F2F2F2;\n"
"}\n"
"")
        self.workerIdLineEdit.setObjectName("workerIdLineEdit")
        self.nextButton = QtWidgets.QPushButton(self.page_3)
        self.nextButton.setGeometry(QtCore.QRect(270, 197, 91, 31))
        self.nextButton.setStyleSheet("#nextButton{\n"
"background-color:rgb(0,174,236);\n"
"color:white;\n"
"border:0px;\n"
"border-radius:5px;\n"
"}")
        self.nextButton.setObjectName("nextButton")
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.warningLabel3 = QtWidgets.QLabel(self.page_4)
        self.warningLabel3.setGeometry(QtCore.QRect(80, 200, 120, 25))
        self.warningLabel3.setStyleSheet("#warningLabel3{\n"
                                         "border: 0px;\n"
                                         "color: rgb(217,48,37);\n"
                                         "}")
        self.warningLabel3.setObjectName("warningLabel3")
        self.yearlineEdit = QtWidgets.QLineEdit(self.page_4)
        self.yearlineEdit.setGeometry(QtCore.QRect(40, 80, 71, 41))
        self.yearlineEdit.setStyleSheet("* {\n"
"    outline: none;\n"
"}\n"
"\n"
"QDialog {\n"
"    background: #D6DBE9;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #A0A0A0; /* 边框宽度为1px，颜色为#A0A0A0 */\n"
"    border-radius: 3px; /* 边框圆角 */\n"
"    padding-left: 5px; /* 文本距离左边界有5px */\n"
"    background-color: white; /* 背景颜色 */\n"
"    color: #A0A0A0; /* 文本颜色 */\n"
"    selection-background-color: #A0A0A0; /* 选中文本的背景颜色 */\n"
"    selection-color: #F2F2F2; /* 选中文本的颜色 */\n"
"    font-family: \"Microsoft YaHei\"; /* 文本字体族 */\n"
"    font-size: 10pt; /* 文本字体大小 */\n"
"}\n"
"\n"
"QLineEdit:hover { /* 鼠标悬浮在QLineEdit时的状态 */\n"
"    border: 1px solid #298DFF;\n"
"    border-radius: 3px;\n"
"    background-color: white;\n"
"    color: #298DFF;\n"
"    selection-background-color: #298DFF;\n"
"    selection-color: #F2F2F2;\n"
"}\n"
"\n"
"QLineEdit[echoMode=\"2\"] { /* QLineEdit有输入掩码时的状态 */\n"
"    lineedit-password-character: 9679;\n"
"    lineedit-password-mask-delay: 2000;\n"
"}\n"
"\n"
"QLineEdit:disabled { /* QLineEdit在禁用时的状态 */\n"
"    border: 1px solid #CDCDCD;\n"
"    background-color: #CDCDCD;\n"
"    color: #B4B4B4;\n"
"}\n"
"\n"
"QLineEdit:read-only { /* QLineEdit在只读时的状态 */\n"
"    background-color: #CDCDCD;\n"
"    color: #F2F2F2;\n"
"}\n"
"")
        self.yearlineEdit.setObjectName("yearlineEdit")
        self.label_5 = QtWidgets.QLabel(self.page_4)
        self.label_5.setGeometry(QtCore.QRect(78, 30, 201, 20))
        self.label_5.setStyleSheet("#label_5{\n"
"font: 11pt \"黑体\";\n"
"}")
        self.label_5.setObjectName("label_5")
        self.daylineEdit = QtWidgets.QLineEdit(self.page_4)
        self.daylineEdit.setGeometry(QtCore.QRect(247, 79, 71, 41))
        self.daylineEdit.setStyleSheet("* {\n"
"    outline: none;\n"
"}\n"
"\n"
"QDialog {\n"
"    background: #D6DBE9;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #A0A0A0; /* 边框宽度为1px，颜色为#A0A0A0 */\n"
"    border-radius: 3px; /* 边框圆角 */\n"
"    padding-left: 5px; /* 文本距离左边界有5px */\n"
"    background-color: white; /* 背景颜色 */\n"
"    color: #A0A0A0; /* 文本颜色 */\n"
"    selection-background-color: #A0A0A0; /* 选中文本的背景颜色 */\n"
"    selection-color: #F2F2F2; /* 选中文本的颜色 */\n"
"    font-family: \"Microsoft YaHei\"; /* 文本字体族 */\n"
"    font-size: 10pt; /* 文本字体大小 */\n"
"}\n"
"\n"
"QLineEdit:hover { /* 鼠标悬浮在QLineEdit时的状态 */\n"
"    border: 1px solid #298DFF;\n"
"    border-radius: 3px;\n"
"    background-color: white;\n"
"    color: #298DFF;\n"
"    selection-background-color: #298DFF;\n"
"    selection-color: #F2F2F2;\n"
"}\n"
"\n"
"QLineEdit[echoMode=\"2\"] { /* QLineEdit有输入掩码时的状态 */\n"
"    lineedit-password-character: 9679;\n"
"    lineedit-password-mask-delay: 2000;\n"
"}\n"
"\n"
"QLineEdit:disabled { /* QLineEdit在禁用时的状态 */\n"
"    border: 1px solid #CDCDCD;\n"
"    background-color: #CDCDCD;\n"
"    color: #B4B4B4;\n"
"}\n"
"\n"
"QLineEdit:read-only { /* QLineEdit在只读时的状态 */\n"
"    background-color: #CDCDCD;\n"
"    color: #F2F2F2;\n"
"}\n"
"")
        self.daylineEdit.setObjectName("daylineEdit")
        self.sexlineEdit = QtWidgets.QLineEdit(self.page_4)
        self.sexlineEdit.setGeometry(QtCore.QRect(40, 138, 281, 41))
        self.sexlineEdit.setStyleSheet("* {\n"
"    outline: none;\n"
"}\n"
"\n"
"QDialog {\n"
"    background: #D6DBE9;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #A0A0A0; /* 边框宽度为1px，颜色为#A0A0A0 */\n"
"    border-radius: 3px; /* 边框圆角 */\n"
"    padding-left: 5px; /* 文本距离左边界有5px */\n"
"    background-color: white; /* 背景颜色 */\n"
"    color: #A0A0A0; /* 文本颜色 */\n"
"    selection-background-color: #A0A0A0; /* 选中文本的背景颜色 */\n"
"    selection-color: #F2F2F2; /* 选中文本的颜色 */\n"
"    font-family: \"Microsoft YaHei\"; /* 文本字体族 */\n"
"    font-size: 10pt; /* 文本字体大小 */\n"
"}\n"
"\n"
"QLineEdit:hover { /* 鼠标悬浮在QLineEdit时的状态 */\n"
"    border: 1px solid #298DFF;\n"
"    border-radius: 3px;\n"
"    background-color: white;\n"
"    color: #298DFF;\n"
"    selection-background-color: #298DFF;\n"
"    selection-color: #F2F2F2;\n"
"}\n"
"\n"
"QLineEdit[echoMode=\"2\"] { /* QLineEdit有输入掩码时的状态 */\n"
"    lineedit-password-character: 9679;\n"
"    lineedit-password-mask-delay: 2000;\n"
"}\n"
"\n"
"QLineEdit:disabled { /* QLineEdit在禁用时的状态 */\n"
"    border: 1px solid #CDCDCD;\n"
"    background-color: #CDCDCD;\n"
"    color: #B4B4B4;\n"
"}\n"
"\n"
"QLineEdit:read-only { /* QLineEdit在只读时的状态 */\n"
"    background-color: #CDCDCD;\n"
"    color: #F2F2F2;\n"
"}\n"
"")
        self.sexlineEdit.setObjectName("sexlineEdit")
        self.nextButton_2 = QtWidgets.QPushButton(self.page_4)
        self.nextButton_2.setGeometry(QtCore.QRect(280, 200, 91, 31))
        self.nextButton_2.setStyleSheet("#nextButton_2{\n"
"background-color:rgb(0,174,236);\n"
"color:white;\n"
"border:0px;\n"
"border-radius:5px;\n"
"}")
        self.nextButton_2.setObjectName("nextButton_2")
        self.monthlineEdit = QtWidgets.QLineEdit(self.page_4)
        self.monthlineEdit.setGeometry(QtCore.QRect(140, 80, 71, 41))
        self.monthlineEdit.setStyleSheet("* {\n"
"    outline: none;\n"
"}\n"
"\n"
"QDialog {\n"
"    background: #D6DBE9;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #A0A0A0; /* 边框宽度为1px，颜色为#A0A0A0 */\n"
"    border-radius: 3px; /* 边框圆角 */\n"
"    padding-left: 5px; /* 文本距离左边界有5px */\n"
"    background-color: white; /* 背景颜色 */\n"
"    color: #A0A0A0; /* 文本颜色 */\n"
"    selection-background-color: #A0A0A0; /* 选中文本的背景颜色 */\n"
"    selection-color: #F2F2F2; /* 选中文本的颜色 */\n"
"    font-family: \"Microsoft YaHei\"; /* 文本字体族 */\n"
"    font-size: 10pt; /* 文本字体大小 */\n"
"}\n"
"\n"
"QLineEdit:hover { /* 鼠标悬浮在QLineEdit时的状态 */\n"
"    border: 1px solid #298DFF;\n"
"    border-radius: 3px;\n"
"    background-color: white;\n"
"    color: #298DFF;\n"
"    selection-background-color: #298DFF;\n"
"    selection-color: #F2F2F2;\n"
"}\n"
"\n"
"QLineEdit[echoMode=\"2\"] { /* QLineEdit有输入掩码时的状态 */\n"
"    lineedit-password-character: 9679;\n"
"    lineedit-password-mask-delay: 2000;\n"
"}\n"
"\n"
"QLineEdit:disabled { /* QLineEdit在禁用时的状态 */\n"
"    border: 1px solid #CDCDCD;\n"
"    background-color: #CDCDCD;\n"
"    color: #B4B4B4;\n"
"}\n"
"\n"
"QLineEdit:read-only { /* QLineEdit在只读时的状态 */\n"
"    background-color: #CDCDCD;\n"
"    color: #F2F2F2;\n"
"}\n"
"")
        self.monthlineEdit.setObjectName("monthlineEdit")
        self.stackedWidget_2.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.warningLabel4 = QtWidgets.QLabel(self.page_5)
        self.warningLabel4.setGeometry(QtCore.QRect(80, 200, 120, 25))
        self.warningLabel4.setStyleSheet("#warningLabel4{\n"
                                         "border: 0px;\n"
                                         "color: rgb(217,48,37);\n"
                                         "}")
        self.warningLabel4.setObjectName("warningLabel4")
        self.createUserLineEdit = QtWidgets.QLineEdit(self.page_5)
        self.createUserLineEdit.setGeometry(QtCore.QRect(80, 40, 231, 41))
        self.createUserLineEdit.setStyleSheet("* {\n"
"    outline: none;\n"
"}\n"
"\n"
"QDialog {\n"
"    background: #D6DBE9;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #A0A0A0; /* 边框宽度为1px，颜色为#A0A0A0 */\n"
"    border-radius: 3px; /* 边框圆角 */\n"
"    padding-left: 5px; /* 文本距离左边界有5px */\n"
"    background-color: white; /* 背景颜色 */\n"
"    color: #A0A0A0; /* 文本颜色 */\n"
"    selection-background-color: #A0A0A0; /* 选中文本的背景颜色 */\n"
"    selection-color: #F2F2F2; /* 选中文本的颜色 */\n"
"    font-family: \"Microsoft YaHei\"; /* 文本字体族 */\n"
"    font-size: 10pt; /* 文本字体大小 */\n"
"}\n"
"\n"
"QLineEdit:hover { /* 鼠标悬浮在QLineEdit时的状态 */\n"
"    border: 1px solid #298DFF;\n"
"    border-radius: 3px;\n"
"    background-color: white;\n"
"    color: #298DFF;\n"
"    selection-background-color: #298DFF;\n"
"    selection-color: #F2F2F2;\n"
"}\n"
"\n"
"QLineEdit[echoMode=\"2\"] { /* QLineEdit有输入掩码时的状态 */\n"
"    lineedit-password-character: 9679;\n"
"    lineedit-password-mask-delay: 2000;\n"
"}\n"
"\n"
"QLineEdit:disabled { /* QLineEdit在禁用时的状态 */\n"
"    border: 1px solid #CDCDCD;\n"
"    background-color: #CDCDCD;\n"
"    color: #B4B4B4;\n"
"}\n"
"\n"
"QLineEdit:read-only { /* QLineEdit在只读时的状态 */\n"
"    background-color: #CDCDCD;\n"
"    color: #F2F2F2;\n"
"}\n"
"")
        self.createUserLineEdit.setObjectName("createUserLineEdit")
        self.createPassLineEdit = QtWidgets.QLineEdit(self.page_5)
        self.createPassLineEdit.setGeometry(QtCore.QRect(80, 90, 231, 41))
        self.createPassLineEdit.setStyleSheet("* {\n"
"    outline: none;\n"
"}\n"
"\n"
"QDialog {\n"
"    background: #D6DBE9;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #A0A0A0; /* 边框宽度为1px，颜色为#A0A0A0 */\n"
"    border-radius: 3px; /* 边框圆角 */\n"
"    padding-left: 5px; /* 文本距离左边界有5px */\n"
"    background-color: white; /* 背景颜色 */\n"
"    color: #A0A0A0; /* 文本颜色 */\n"
"    selection-background-color: #A0A0A0; /* 选中文本的背景颜色 */\n"
"    selection-color: #F2F2F2; /* 选中文本的颜色 */\n"
"    font-family: \"Microsoft YaHei\"; /* 文本字体族 */\n"
"    font-size: 10pt; /* 文本字体大小 */\n"
"}\n"
"\n"
"QLineEdit:hover { /* 鼠标悬浮在QLineEdit时的状态 */\n"
"    border: 1px solid #298DFF;\n"
"    border-radius: 3px;\n"
"    background-color: white;\n"
"    color: #298DFF;\n"
"    selection-background-color: #298DFF;\n"
"    selection-color: #F2F2F2;\n"
"}\n"
"\n"
"QLineEdit[echoMode=\"2\"] { /* QLineEdit有输入掩码时的状态 */\n"
"    lineedit-password-character: 9679;\n"
"    lineedit-password-mask-delay: 2000;\n"
"}\n"
"\n"
"QLineEdit:disabled { /* QLineEdit在禁用时的状态 */\n"
"    border: 1px solid #CDCDCD;\n"
"    background-color: #CDCDCD;\n"
"    color: #B4B4B4;\n"
"}\n"
"\n"
"QLineEdit:read-only { /* QLineEdit在只读时的状态 */\n"
"    background-color: #CDCDCD;\n"
"    color: #F2F2F2;\n"
"}\n"
"")
        self.createPassLineEdit.setObjectName("createPassLineEdit")
        self.rootPasswordButton = QtWidgets.QLineEdit(self.page_5)
        self.rootPasswordButton.setGeometry(QtCore.QRect(80, 145, 231, 41))
        self.rootPasswordButton.setStyleSheet("* {\n"
"    outline: none;\n"
"}\n"
"\n"
"QDialog {\n"
"    background: #D6DBE9;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #A0A0A0; /* 边框宽度为1px，颜色为#A0A0A0 */\n"
"    border-radius: 3px; /* 边框圆角 */\n"
"    padding-left: 5px; /* 文本距离左边界有5px */\n"
"    background-color: white; /* 背景颜色 */\n"
"    color: #A0A0A0; /* 文本颜色 */\n"
"    selection-background-color: #A0A0A0; /* 选中文本的背景颜色 */\n"
"    selection-color: #F2F2F2; /* 选中文本的颜色 */\n"
"    font-family: \"Microsoft YaHei\"; /* 文本字体族 */\n"
"    font-size: 10pt; /* 文本字体大小 */\n"
"}\n"
"\n"
"QLineEdit:hover { /* 鼠标悬浮在QLineEdit时的状态 */\n"
"    border: 1px solid #298DFF;\n"
"    border-radius: 3px;\n"
"    background-color: white;\n"
"    color: #298DFF;\n"
"    selection-background-color: #298DFF;\n"
"    selection-color: #F2F2F2;\n"
"}\n"
"\n"
"QLineEdit[echoMode=\"2\"] { /* QLineEdit有输入掩码时的状态 */\n"
"    lineedit-password-character: 9679;\n"
"    lineedit-password-mask-delay: 2000;\n"
"}\n"
"\n"
"QLineEdit:disabled { /* QLineEdit在禁用时的状态 */\n"
"    border: 1px solid #CDCDCD;\n"
"    background-color: #CDCDCD;\n"
"    color: #B4B4B4;\n"
"}\n"
"\n"
"QLineEdit:read-only { /* QLineEdit在只读时的状态 */\n"
"    background-color: #CDCDCD;\n"
"    color: #F2F2F2;\n"
"}\n"
"")
        self.rootPasswordButton.setObjectName("rootPasswordButton")
        self.label_6 = QtWidgets.QLabel(self.page_5)
        self.label_6.setGeometry(QtCore.QRect(130, 10, 111, 20))
        self.label_6.setStyleSheet("#label_6{\n"
"font: 11pt \"黑体\";\n"
"}")
        self.label_6.setObjectName("label_6")
        self.okButton = QtWidgets.QPushButton(self.page_5)
        self.okButton.setGeometry(QtCore.QRect(270, 200, 91, 31))
        self.okButton.setStyleSheet("#okButton{\n"
"background-color:rgb(0,174,236);\n"
"color:white;\n"
";\n"
"border-radius:5px;\n"
"}\n"
"#okButton::hover{\n"
"background-color:rgb(64,197,243);\n"
"}")
        self.okButton.setObjectName("okButton")
        self.stackedWidget_2.addWidget(self.page_5)
        self.stackedWidget.addWidget(self.page_2)
       # self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1077, 26))
        self.menubar.setObjectName("menubar")
#        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
#        self.setStatusBar(self.statusbar)

#        self.retranslateUi(self)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(self)
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.password_button.setText(_translate("MainWindow", "密码登录"))
        self.message_button.setText(_translate("MainWindow", "用户注册"))
        self.label.setText(_translate("MainWindow", "账号"))
        self.label_2.setText(_translate("MainWindow", "密码"))
        self.user_linedit.setPlaceholderText(_translate("MainWindow", "请输入账号"))
        self.password_linedit.setPlaceholderText(_translate("MainWindow", "请输入密码"))
        self.radioButton.setText(_translate("MainWindow", "在线模式"))
        self.radioButton_2.setText(_translate("MainWindow", "离线模式"))
        self.login_button.setText(_translate("MainWindow", "登录"))
        self.label_3.setText(_translate("MainWindow", "账号注册"))
        self.warningLabel.setText(_translate("MainWindow", ""))
        self.label_4.setText(_translate("MainWindow", "请输入您的信息"))
        self.nameLineEdit.setPlaceholderText(_translate("MainWindow", "请输入姓名"))
        self.workerIdLineEdit.setPlaceholderText(_translate("MainWindow", "请输入工号"))
        self.nextButton.setText(_translate("MainWindow", "下一步"))
        self.yearlineEdit.setPlaceholderText(_translate("MainWindow", "年"))
        self.sexlineEdit.setPlaceholderText(_translate("MainWindow", "请输入男/女"))
        self.label_5.setText(_translate("MainWindow", "输入您的生日日期和性别"))
        self.daylineEdit.setPlaceholderText(_translate("MainWindow", "日"))
        self.sexlineEdit.setPlaceholderText(_translate("MainWindow", "性别"))
        self.nextButton_2.setText(_translate("MainWindow", "下一步"))
        self.monthlineEdit.setPlaceholderText(_translate("MainWindow", "月"))
        self.createUserLineEdit.setPlaceholderText(_translate("MainWindow", "请输入账号"))
        self.createPassLineEdit.setPlaceholderText(_translate("MainWindow", "请输入密码"))
        self.rootPasswordButton.setPlaceholderText(_translate("MainWindow", "请输入权限密码(选填)"))
        self.label_6.setText(_translate("MainWindow", "创建账号密码"))
        self.okButton.setText(_translate("MainWindow", "确认"))

    def change_window1(self):
        self.stackedWidget.setCurrentIndex(1)

    def change_window0(self):
        self.stackedWidget.setCurrentIndex(0)

    def connect(self):
         self.message_button.clicked.connect(self.change_window1)
         self.password_button.clicked.connect(self.change_window0)

if __name__ == '__main__':
    app = QApplication(sys.argv)
    login_window = Login_window()
    sys.exit(app.exec_())



import src.demo_rc

